name: Java CI

on:
  # Trigger the workflow on push or pull request,
  # but only for release or test relevant branches.
  push:
    branches:
      - 'alpha/**' 
      - 'beta/**' 
      - 'release/**' 
      - 'test/**' 
  pull_request:
    branches:
      - 'alpha/**' 
      - 'beta/**' 
      - 'release/**' 
      - 'test/**' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Restore cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
    - name: Setup Gradle
      run: chmod +x gradlew
    - name: Gradle Build
      run: ./gradlew build
