name: Java CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - 'alpha/**' 
      - 'beta/**' 
      - 'release/**' 
  pull_request:
    branches:
      - 'alpha/**' 
      - 'beta/**' 
      - 'release/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
    - name: Setup Build
      run: chmod 777 gradlew
    - name: Build with Gradle
      run: ./gradlew build
